flows:
  # - type: playground
  #   id: Invoice_Based_Loan_Foreclosure
  #   usecase: UNIFIED CREDIT
  #   tags:
  #     - WORKBENCH
  #     - WITH_ACCOUNT_AGGREGATOR
  #     - REPORTABLE
  #     - INVOICE BASED LOAN
  #   description: Invoice Based Loan - Loan Foreclosure
  #   config:
  #     $ref: ./UNIFIED CREDIT/Invoice_Based_Loan_Foreclosure.yaml
  # - type: playground
  #   id: Invoice_Based_Loan_Foreclosure_Without_AA"
  #   usecase: UNIFIED CREDIT
  #   tags:
  #     - WORKBENCH
  #     - WITHOUT_ACCOUNT_AGGREGATOR
  #     - REPORTABLE
  #     - INVOICE BASED LOAN
  #   description: Invoice Based Loan - Loan Foreclosure
  #   config:
  #     $ref: ./UNIFIED CREDIT/Invoice_Based_Loan_Foreclosure_Without_AA_.yaml
  # - type: playground
  #   id: Invoice_Based_Loan_Missed_EMI
  #   usecase: UNIFIED CREDIT
  #   tags:
  #     - WORKBENCH
  #     - WITH_ACCOUNT_AGGREGATOR
  #     - REPORTABLE
  #     - INVOICE BASED LOAN
  #   description: Invoice Based Loan - Loan Foreclosure
  #   config:
  #     $ref: ./UNIFIED CREDIT/Invoice_Based_Loan_Missed_EMI.yaml
  # - type: playground
  #   id: Invoice_Based_Loan_Missed_EMI_Without_AA
  #   usecase: UNIFIED CREDIT
  #   tags:
  #     - WORKBENCH
  #     - WITHOUT_ACCOUNT_AGGREGATOR
  #     - REPORTABLE
  #     - INVOICE BASED LOAN
  #   description: Invoice Based Loan - Missed EMI Payment
  #   config:
  #     $ref: ./UNIFIED CREDIT/Invoice_Based_Loan_Missed_EMI_Without_AA.yaml
  # - type: playground
  #   id: Invoice_Based_Loan_Pre_Part_Payment
  #   usecase: UNIFIED CREDIT
  #   tags:
  #     - WORKBENCH
  #     - WITH_ACCOUNT_AGGREGATOR
  #     - REPORTABLE
  #     - INVOICE BASED LOAN
  #   description: Invoice Based Loan - Loan Foreclosure
  #   config:
  #     $ref: ./UNIFIED CREDIT/Invoice_Based_Loan_Pre_Part_Payment.yaml
  # - type: playground
  #   id: Invoice_Based_Loan_Pre_Part_Payment_Without_AA
  #   usecase: UNIFIED CREDIT
  #   tags:
  #     - WORKBENCH
  #     - WITHOUT_ACCOUNT_AGGREGATOR
  #     - REPORTABLE
  #     - INVOICE BASED LOAN
  #   description: Invoice Based Loan - Pre-Part Payment
  #   config:
  #     $ref: ./UNIFIED CREDIT/Invoice_Based_Loan_Pre_Part_Payment_Without_AA.yaml
  # - type: playground
  #   id: Invoice_Based_Loan_With_AA
  #   usecase: UNIFIED CREDIT
  #   tags:
  #     - WORKBENCH
  #     - WITH_ACCOUNT_AGGREGATOR
  #     - REPORTABLE
  #     - INVOICE BASED LOAN
  #   description: Invoice Based Loan with Account Aggregator & monitoring consent
  #   config:
  #     $ref: ./UNIFIED CREDIT/Invoice_Based_Loan_With_AA.yaml
  # - type: playground
  #   id: Invoice_Based_Loan_Without_AA
  #   usecase: UNIFIED CREDIT
  #   tags:
  #     - WORKBENCH
  #     - WITH_ACCOUNT_AGGREGATOR
  #     - REPORTABLE
  #     - INVOICE BASED LOAN
  #   description: Invoice Based Loan - flow without Account Aggregator
  #   config:
  #     $ref: ./UNIFIED CREDIT/Invoice_Based_Loan_Without_AA.yaml
  # - type: playground
  #   id: Personal_Loan_Foreclosure_With_AA
  #   usecase: UNIFIED CREDIT
  #   tags:
  #     - WORKBENCH
  #     - WITH_ACCOUNT_AGGREGATOR
  #     - REPORTABLE
  #     - PERSONAL LOAN
  #   description: Personal Loan - Loan Foreclosure
  #   config:
  #     $ref: ./UNIFIED CREDIT/Personal_Loan_Foreclosure_With_AA.yaml
  # - type: playground
  #   id: Personal_Loan_Foreclosure_Without_AA"
  #   usecase: UNIFIED CREDIT
  #   tags:
  #     - WORKBENCH
  #     - WITHOUT_ACCOUNT_AGGREGATOR
  #     - REPORTABLE
  #     - PERSONAL LOAN
  #   description: Personal Loan - Loan Foreclosure
  #   config:
  #     $ref: ./UNIFIED CREDIT/Personal_Loan_Foreclosure_Without_AA_.yaml
  # - type: playground
  #   id: Personal_Loan_Missed_EMI
  #   usecase: UNIFIED CREDIT
  #   tags:
  #     - WORKBENCH
  #     - WITH_ACCOUNT_AGGREGATOR
  #     - REPORTABLE
  #     - PERSONAL LOAN
  #   description: Personal Loan - Missed EMI Payment
  #   config:
  #     $ref: ./UNIFIED CREDIT/Personal_Loan_Missed_EMI.yaml
  # - type: playground
  #   id: Personal_Loan_Missed_EMI_Without_AA
  #   usecase: UNIFIED CREDIT
  #   tags:
  #     - WORKBENCH
  #     - WITHOUT_ACCOUNT_AGGREGATOR
  #     - REPORTABLE
  #     - PERSONAL LOAN
  #   description: Personal Loan - Missed EMI Payment
  #   config:
  #     $ref: ./UNIFIED CREDIT/Personal_Loan_Missed_EMI_Without_AA.yaml
  # - type: playground
  #   id: Personal_Loan_Multiple_Offers
  #   usecase: UNIFIED CREDIT
  #   tags:
  #     - WORKBENCH
  #   description: Personal Loan - Multiple Offers (Bureau Consent & AA Verification)
  #   config:
  #     $ref: ./UNIFIED CREDIT/Personal_Loan_Multiple_Offers.yaml
  # - type: playground
  #   id: Personal_Loan_Offline_And_Online
  #   usecase: UNIFIED CREDIT
  #   tags:
  #     - WORKBENCH
  #     - WITH_ACCOUNT_AGGREGATOR
  #     - REPORTABLE
  #   description: Personal Loan - Offline & Online Hybrid Verification
  #   config:
  #     $ref: ./UNIFIED CREDIT/Personal_Loan_Offline_And_Online.yaml
  # - type: playground
  #   id: Personal_Loan_Pre_Part_Payment
  #   usecase: UNIFIED CREDIT
  #   tags:
  #     - WORKBENCH
  #     - WITH_ACCOUNT_AGGREGATOR
  #     - REPORTABLE
  #     - PERSONAL LOAN
  #   description: Personal Loan - Pre-Part Payment
  #   config:
  #     $ref: ./UNIFIED CREDIT/Personal_Loan_Pre_Part_Payment.yaml
  # - type: playground
  #   id: Personal_Loan_Pre_Part_Payment_Without_AA
  #   usecase: UNIFIED CREDIT
  #   tags:
  #     - WORKBENCH
  #     - WITHOUT_ACCOUNT_AGGREGATOR
  #     - REPORTABLE
  #     - PERSONAL LOAN
  #   description: Personal Loan - Pre-Part Payment
  #   config:
  #     $ref: ./UNIFIED CREDIT/Personal_Loan_Pre_Part_Payment_Without_AA.yaml
  # - type: playground
  #   id: Personal_Loan_With_AA_And_Monitoring_Consent
  #   usecase: UNIFIED CREDIT
  #   tags:
  #     - WORKBENCH
  #     - WITH_ACCOUNT_AGGREGATOR
  #     - REPORTABLE
  #     - PERSONAL LOAN
  #   description: Personal Loan with Account Aggregator & monitoring consent
  #   config:
  #     $ref: ./UNIFIED CREDIT/Personal_Loan_With_AA_And_Monitoring_Consent.yaml
  # - type: playground
  #   id: Personal_Loan_Without_AA_And_Monitoring_Consent
  #   usecase: UNIFIED CREDIT
  #   tags:
  #     - WORKBENCH
  #     - WITHOUT_ACCOUNT_AGGREGATOR
  #     - REPORTABLE
  #   description: Personal Loan flow without Account Aggregator
  #   config:
  #     $ref: ./UNIFIED CREDIT/Personal_Loan_Without_AA_And_Monitoring_Consent.yaml
  # - type: playground
  #   id: Personal_Loan_Without_Acount_Monitoring
  #   usecase: UNIFIED CREDIT
  #   tags:
  #     - WORKBENCH
  #     - WITH_ACCOUNT_AGGREGATOR
  #     - REPORTABLE
  #   description: Personal Loan with Account Aggregator & monitoring consent
  #   config:
  #     $ref: ./UNIFIED CREDIT/Personal_Loan_Without_Acount_Monitoring.yaml
  # - type: playground
  #   id: Purchase_Finance_Foreclosure
  #   usecase: UNIFIED CREDIT
  #   tags:
  #     - WORKBENCH
  #     - WITH_ACCOUNT_AGGREGATOR
  #     - REPORTABLE
  #     - PURCHASE FINANCE
  #   description: Purchase Finance - Loan Foreclosure
  #   config:
  #     $ref: ./UNIFIED CREDIT/Purchase_Finance_Foreclosure.yaml
  # - type: playground
  #   id: Purchase_Finance_Foreclosure_Without_AA"
  #   usecase: UNIFIED CREDIT
  #   tags:
  #     - WORKBENCH
  #     - WITHOUT_ACCOUNT_AGGREGATOR
  #     - REPORTABLE
  #     - PURCHASE FINANCE
  #   description: Purchase Finance - Loan Foreclosure
  #   config:
  #     $ref: ./UNIFIED CREDIT/Purchase_Finance_Foreclosure_Without_AA_.yaml
  # - type: playground
  #   id: Purchase_Finance_Missed_EMI
  #   usecase: UNIFIED CREDIT
  #   tags:
  #     - WORKBENCH
  #     - WITH_ACCOUNT_AGGREGATOR
  #     - REPORTABLE
  #     - PURCHASE FINANCE
  #   description: Purchase Finance - Missed EMI Payment
  #   config:
  #     $ref: ./UNIFIED CREDIT/Purchase_Finance_Missed_EMI.yaml
  # - type: playground
  #   id: Purchase_Finance_Missed_EMI_Without_AA
  #   usecase: UNIFIED CREDIT
  #   tags:
  #     - WORKBENCH
  #     - WITHOUT_ACCOUNT_AGGREGATOR
  #     - REPORTABLE
  #     - PURCHASE FINANCE
  #   description: Purchase Finance - Missed EMI Payment
  #   config:
  #     $ref: ./UNIFIED CREDIT/Purchase_Finance_Missed_EMI_Without_AA.yaml
  # - type: playground
  #   id: Purchase_Finance_Multiple_Offers
  #   usecase: UNIFIED CREDIT
  #   tags:
  #     - WORKBENCH
  #   description: Purchase Finance - Multiple Offers (Bureau Consent & AA Verification)
  #   config:
  #     $ref: ./UNIFIED CREDIT/Purchase_Finance_Multiple_Offers.yaml
  # - type: playground
  #   id: Purchase_Finance_Pre_Part_Payment
  #   usecase: UNIFIED CREDIT
  #   tags:
  #     - WORKBENCH
  #     - WITH_ACCOUNT_AGGREGATOR
  #     - REPORTABLE
  #     - PURCHASE FINANCE
  #   description: Purchase Finance - Pre-Part Payment
  #   config:
  #     $ref: ./UNIFIED CREDIT/Purchase_Finance_Pre_Part_Payment.yaml
  # - type: playground
  #   id: Purchase_Finance_Pre_Part_Payment_Without_AA
  #   usecase: UNIFIED CREDIT
  #   tags:
  #     - WORKBENCH
  #     - WITHOUT_ACCOUNT_AGGREGATOR
  #     - REPORTABLE
  #     - PURCHASE FINANCE
  #   description: Purchase Finance - Pre-Part Payment
  #   config:
  #     $ref: ./UNIFIED CREDIT/Purchase_Finance_Pre_Part_Payment_Without_AA.yaml
  # - type: playground
  #   id: Purchase_Finance_With_AA
  #   usecase: UNIFIED CREDIT
  #   tags:
  #     - WORKBENCH
  #     - WITH_ACCOUNT_AGGREGATOR
  #     - REPORTABLE
  #     - PURCHASE FINANCE
  #   description: Purchase Finance with Account Aggregator & monitoring consent
  #   config:
  #     $ref: ./UNIFIED CREDIT/Purchase_Finance_With_AA.yaml
  # - type: playground
  #   id: Purchase_Finance_Without_AA
  #   usecase: UNIFIED CREDIT
  #   tags:
  #     - WORKBENCH
  #     - WITH_ACCOUNT_AGGREGATOR
  #     - REPORTABLE
  #     - PURCHASE FINANCE
  #   description: Purchase Finance with Account Aggregator & monitoring consent
  #   config:
  #     $ref: ./UNIFIED CREDIT/Purchase_Finance_Without_AA.yaml
  # - type: playground
  #   id: Unified_Credit_Master_Search
  #   usecase: UNIFIED CREDIT
  #   tags:
  #     - WORKBENCH
  #     - REPORTABLE
  #     - PERSONAL LOAN
  #   description: Unified Credit Master Search
  #   config:
  #     $ref: ./UNIFIED CREDIT/Unified_Credit_Master_Search.yaml

  - type: playground
    id: master_search
    usecase: UNIFIED CREDIT
    tags:
      - WORKBENCH
      - REPORTABLE
    description: Master Search
    config:
      $ref: ./UNIFIED CREDIT/master_search.yaml

  
  - type: playground
    id: business_term_loan_with_aa
    usecase: UNIFIED CREDIT
    tags:
      - WORKBENCH
      - REPORTABLE
      - PERSONAL LOAN
    description: Business Loan Foreclosure - Term Loan with Offline & Online Journey
    config:
      $ref: ./UNIFIED CREDIT/Business_Term_Loan_with_AA.yaml

  - type: playground
    id: business_term_loan_with_aa_missed_emi
    usecase: UNIFIED CREDIT
    tags:
      - WORKBENCH
      - REPORTABLE
      - PERSONAL LOAN
    description: Business Loan Missed EMI - Term Loan with Offline & Online Journey
    config:
      $ref: ./UNIFIED CREDIT/Business_Term_Loan_with_AA_Missed_EMI.yaml

  - type: playground
    id: business_term_loan_with_aa_pre_part
    usecase: UNIFIED CREDIT
    tags:
      - WORKBENCH
      - REPORTABLE
      - PERSONAL LOAN
    description: Business Loan Pre-Part - Term Loan with Offline & Online Journey
    config:
      $ref: ./UNIFIED CREDIT/Business_Term_Loan_with_AA_Pre_Part.yaml        


  - type: playground
    id: business_term_loan_with_offline_online
    usecase: UNIFIED CREDIT
    tags:
      - WORKBENCH
      - REPORTABLE
      - PERSONAL LOAN
    description: Business Loan - Term Loan with Offline & Online Journey
    config:
      $ref: ./UNIFIED CREDIT/Business_Term_Loan_with_offline_online_journey.yaml

  - type: playground
    id: business_term_loan_without_aa
    usecase: UNIFIED CREDIT
    tags:
      - WORKBENCH
      - REPORTABLE
      - PERSONAL LOAN
    description: Business Loan - Term Loan without Account Aggregator
    config:
      $ref: ./UNIFIED CREDIT/Business_Term_Loan_without_aa.yaml

  - type: playground
    id: business_term_loan_with_gst_data
    usecase: UNIFIED CREDIT
    tags:
      - WORKBENCH
      - REPORTABLE
      - PERSONAL LOAN
    description: Business Loan - Term Loan with GST Data
    config:
      $ref: ./UNIFIED CREDIT/Business_Term_Loan_with_GST_data.yaml        

  - type: playground
    id: lamf_credit_line_journey
    usecase: UNIFIED CREDIT
    tags:
      - WORKBENCH
      - REPORTABLE
    description: LAMF - Credit Line
    config:
      $ref: ./UNIFIED CREDIT/LAMF_credit_line_journey_deployment_config.yaml

  - type: playground
    id: lamf_credit_line_with_mfc_offline_journey
    usecase: UNIFIED CREDIT
    tags:
      - WORKBENCH
      - REPORTABLE
    description: LAMF - Credit Line with MFC (Offline Journey)
    config:
      $ref: ./UNIFIED CREDIT/LAMF_Credit_Line_with_MFC_Offline_Journey.yaml  

  - type: playground
    id: lamf_credit_line_with_mfc_foreclosure
    usecase: UNIFIED CREDIT
    tags:
      - WORKBENCH
      - REPORTABLE
    description: LAMF - Credit Line with MFC_Foreclosure
    config:
      $ref: ./UNIFIED CREDIT/LAMF_Credit_Line_with_MFC.yaml 

  - type: playground
    id: lamf_credit_line_with_mfc_missed_emi
    usecase: UNIFIED CREDIT
    tags:
      - WORKBENCH
      - REPORTABLE
    description: LAMF - Credit Line with MFC_Missed_EMI
    config:
      $ref: ./UNIFIED CREDIT/LAMF_Credit_Line_with_MFC_missed_emi.yaml 

  - type: playground
    id: lamf_credit_line_with_pre_part
    usecase: UNIFIED CREDIT
    tags:
      - WORKBENCH
      - REPORTABLE
    description: LAMF - Credit Line with MFC_Missed_EMI
    config:
      $ref: ./UNIFIED CREDIT/LAMF_Credit_Line_with_MFC_pre_part.yaml             

  - type: playground
    id: lamf_credit_line_with_rta
    usecase: UNIFIED CREDIT
    tags:
      - WORKBENCH
      - REPORTABLE
    description: LAMF - Credit Line with RTA
    config:
      $ref: ./UNIFIED CREDIT/lamf_credit_line_with_rta_deployment_config.yaml       


         

      
